{{- if .Values.celeryBeat.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.projectName }}-celery-beat-{{ .Values.environment }}"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "django-api-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "django-api-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "django-api-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ .Values.projectName }}-celery-beat-ci"
      {{ if eq .Values.environment "prod"}}
      priorityClassName: workload-critical
      {{ else if eq .Values.environment "test"}}
      priorityClassName: test-critical
      {{ else }}
      priorityClassName: dev-critical
      {{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ .Values.projectName }}-celery-beat-{{ .Values.environment }}"
          env:
            - name: DEPLOY_ENV
              value: {{ .Values.environment }}
            - name: ENV
              value: "production"
          envFrom:
            - secretRef:
                name: "{{ .Values.projectName }}-{{ .Values.environment }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.celeryBeat.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
            limits:
              cpu: 100m
              memory: 300Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end -}}