apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.projectName }}-{{ .Values.environment }}-celery-beat"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "django-api-chart.celeryBeatSelectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "django-api-chart.celeryBeatSelectorLabels" . | nindent 4 }}
