apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.projectName }}-{{ .Values.environment }}-celery-worker"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "django-api-chart.celeryWorkerLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      {{ if eq .Values.environment "prod" }}
      targetPort: 8001
      {{ else if eq .Values.environment "test" }}
      targetPort: 7001
      {{ else }}
      targetPort: 6001
      {{ end }}
  selector:
    {{- include "django-api-chart.celeryWorkerSelectorLabels" . | nindent 4 }}
