apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.projectName }}-api"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fastapi-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    {{- include "fastapi-chart.selectorLabels" . | nindent 4 }}
